export enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  UNPROCESSABLE_ENTITY = 422,
  CONFLICT = 409,
};

export enum ErrorCodes {
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',
  REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND",
  NOT_FOUND = "NOT_FOUND",

  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_CLOSED = "ROOM_CLOSED",
}